title: Carbon
tagline: Open-source game and visualization engine

root: /carbon

github_url: https://github.com/savant-nz/carbon
assets_url: https://d36l7sc3rvseh6.cloudfront.net

# Items on the top navigation bar
navigation:
- text: About
  url: /
  url2: /index.html
- text: Downloads
  url: /downloads.html
- text: Screenshots
  url: /screenshots.html
- text: Contact
  url: /contact.html

# Screenshots to display, these are sourced from S3
screenshots:
- filename: 01.jpg
  text: Interactive physics simulation and reflective surfaces.
- filename: 02.jpg
  text: Infinite terrain and atmospheric scattering.

# People to display on the Contact page
people:
- name: Christiaan Gough
  url: mailto:christiaan.gough@gmail.com
  role: Project Manager
- name: Richard Viney
  url: mailto:richard.viney@gmail.com
  role: Lead Developer

# Releases to display on the Downloads page, sorted by date
releases:
- version: 0.1-alpha-2a6a56d
  date: 2022-09-28
- version: 0.1-alpha-e6765f1
  date: 2016-07-15
