#
# This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of the MPL was not
# distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

Import('*')

sources = env.GlobDirectories(
    'BulletCollision',
    'BulletCollision/BroadphaseCollision',
    'BulletCollision/CollisionDispatch',
    'BulletCollision/CollisionShapes',
    'BulletCollision/Gimpact',
    'BulletCollision/NarrowPhaseCollision',
    'BulletDynamics',
    'BulletDynamics/Character',
    'BulletDynamics/ConstraintSolver',
    'BulletDynamics/Dynamics',
    'BulletDynamics/Featherstone',
    'BulletDynamics/MLCPSolvers',
    'BulletDynamics/Vehicle',
    'BulletSoftBody',
    'LinearMath'
)

result = env.StaticLibrary(target=target, source=sources)

Return('result')
