#
# This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of the MPL was not
# distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

Import('*')

sources = env.GlobDirectories(
    'code', 'contrib/clipper', 'contrib/ConvertUTF', 'contrib/irrXML', 'contrib/openddlparser/code',
    'contrib/poly2tri/poly2tri/common', 'contrib/poly2tri/poly2tri/sweep', 'contrib/unzip'
)

# Workaround for crash in Clang when building ASELoader.cpp with -O3 and targeting iOS (problem started with Xcode 7.3)
if platform == 'iOS' and isReleaseBuild:
    newCCFLAGS = ['-O1' if x == '-O3' else x for x in env['CCFLAGS']]

    sources.remove(env.fs.File('code/ASELoader.cpp'))
    sources += env.StaticObject(source='code/ASELoader.cpp', CCFLAGS=newCCFLAGS)

result = env.StaticLibrary(target=target, source=sources)

Return('result')
