#
# This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of the MPL was not
# distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

Import('*')

sources = env.GlobDirectories(
    'code', 'contrib/clipper', 'contrib/ConvertUTF', 'contrib/irrXML', 'contrib/poly2tri/poly2tri/common',
    'contrib/poly2tri/poly2tri/sweep', 'contrib/unzip'
)

result = env.StaticLibrary(target=target, source=sources)

Return('result')
