#!/usr/bin/ruby
#
# This script is run during the install of the Carbon SDK for Mac OS X and is responsible for deleting any currently
# installed SDK.
#

require 'fileutils'

XCODE_PROJECT_TEMPLATES_PATH = "#{ENV['HOME']}/Library/Developer/Xcode/Templates/Project Templates/Mac/Application".freeze

[
  '/Applications/Carbon SDK',
  "#{XCODE_PROJECT_TEMPLATES_PATH}/CarbonEngine Application",
  "#{XCODE_PROJECT_TEMPLATES_PATH}/CarbonEngine iOS Application"
].each do |entry|
  FileUtils.rm_rf entry
end
