/*
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of the MPL was not
 * distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

#pragma once

// This header includes all public headers

#include "CarbonEngine/Common.h"

#include "CarbonEngine/Application.h"
#include "CarbonEngine/Core/BuildInfo.h"
#include "CarbonEngine/Core/CoreEvents.h"
#include "CarbonEngine/Core/Endian.h"
#include "CarbonEngine/Core/Event.h"
#include "CarbonEngine/Core/EventDelegate.h"
#include "CarbonEngine/Core/EventHandler.h"
#include "CarbonEngine/Core/EventManager.h"
#include "CarbonEngine/Core/Exception.h"
#include "CarbonEngine/Core/FileFormatRegistry.h"
#include "CarbonEngine/Core/FileSystem/FileReader.h"
#include "CarbonEngine/Core/FileSystem/FileSystem.h"
#include "CarbonEngine/Core/FileSystem/FileSystemVolume.h"
#include "CarbonEngine/Core/FileSystem/FileWriter.h"
#include "CarbonEngine/Core/FileSystem/LocalDirectoryFileSystemVolume.h"
#include "CarbonEngine/Core/FileSystem/SimpleFileSystemVolume.h"
#include "CarbonEngine/Core/FileSystem/ZipFileSystemVolume.h"
#include "CarbonEngine/Core/InterfaceRegistry.h"
#include "CarbonEngine/Core/Logfile.h"
#include "CarbonEngine/Core/Memory/BlockAllocator.h"
#include "CarbonEngine/Core/Memory/BlockAllocatorSet.h"
#include "CarbonEngine/Core/Memory/MemoryInterceptor.h"
#include "CarbonEngine/Core/Memory/MemoryLeakDetector.h"
#include "CarbonEngine/Core/Memory/MemoryStatistics.h"
#include "CarbonEngine/Core/Memory/MemoryValidator.h"
#include "CarbonEngine/Core/Noncopyable.h"
#include "CarbonEngine/Core/Parameter.h"
#include "CarbonEngine/Core/ParameterArray.h"
#include "CarbonEngine/Core/Runnable.h"
#include "CarbonEngine/Core/SettingsManager.h"
#include "CarbonEngine/Core/StringBase.h"
#include "CarbonEngine/Core/SubclassRegistry.h"
#include "CarbonEngine/Core/Threads/Mutex.h"
#include "CarbonEngine/Core/Threads/Thread.h"
#include "CarbonEngine/Core/UnorderedPointerSet.h"
#include "CarbonEngine/Core/Vector.h"
#include "CarbonEngine/Core/VersionInfo.h"
#include "CarbonEngine/Exporters/ExporterStrings.h"
#include "CarbonEngine/Exporters/ExportInfo.h"
#include "CarbonEngine/Exporters/ExportRunners.h"
#include "CarbonEngine/Exporters/ProgressDialog.h"
#include "CarbonEngine/Game/GameCenter.h"
#include "CarbonEngine/Game/InAppPurchase.h"
#include "CarbonEngine/Game/Pathfinding/AStarTraversal.h"
#include "CarbonEngine/Game/Pathfinding/GridNavigationGraph.h"
#include "CarbonEngine/Game/Pathfinding/HexagonalNavigationGraph.h"
#include "CarbonEngine/Game/Pathfinding/NavigationEdge.h"
#include "CarbonEngine/Game/Pathfinding/NavigationGraph.h"
#include "CarbonEngine/Game/Pathfinding/NavigationNode.h"
#include "CarbonEngine/Game/ScrollingLayer.h"
#include "CarbonEngine/Game/SplashScreen.h"
#include "CarbonEngine/Game/Sprite.h"
#include "CarbonEngine/Geometry/Triangle.h"
#include "CarbonEngine/Geometry/TriangleArray.h"
#include "CarbonEngine/Geometry/TriangleArraySet.h"
#include "CarbonEngine/Globals.h"
#include "CarbonEngine/Graphics/GraphicsInterface.h"
#include "CarbonEngine/Graphics/OpenGLShared/OpenGLBase.h"
#include "CarbonEngine/Graphics/ShaderConstant.h"
#include "CarbonEngine/Graphics/ShaderProgram.h"
#include "CarbonEngine/Graphics/States/CachedState.h"
#include "CarbonEngine/Graphics/States/IndexedCachedState.h"
#include "CarbonEngine/Graphics/States/SimpleCachedState.h"
#include "CarbonEngine/Graphics/States/StateCacher.h"
#include "CarbonEngine/Graphics/States/States.h"
#include "CarbonEngine/Graphics/States/StateTypes.h"
#include "CarbonEngine/Image/Image.h"
#include "CarbonEngine/Image/ImageFormatRegistry.h"
#include "CarbonEngine/Image/LightmapPacker.h"
#include "CarbonEngine/Math/AABB.h"
#include "CarbonEngine/Math/Color.h"
#include "CarbonEngine/Math/ConvexHull.h"
#include "CarbonEngine/Math/HashFunctions.h"
#include "CarbonEngine/Math/Interpolate.h"
#include "CarbonEngine/Math/InterpolatedLookupTable.h"
#include "CarbonEngine/Math/Line.h"
#include "CarbonEngine/Math/MathCommon.h"
#include "CarbonEngine/Math/Matrix3.h"
#include "CarbonEngine/Math/Matrix4.h"
#include "CarbonEngine/Math/Noise.h"
#include "CarbonEngine/Math/Plane.h"
#include "CarbonEngine/Math/Quaternion.h"
#include "CarbonEngine/Math/RandomNumberGenerator.h"
#include "CarbonEngine/Math/Ray.h"
#include "CarbonEngine/Math/Rect.h"
#include "CarbonEngine/Math/SimpleTransform.h"
#include "CarbonEngine/Math/Sphere.h"
#include "CarbonEngine/Math/Vec2.h"
#include "CarbonEngine/Math/Vec2i.h"
#include "CarbonEngine/Math/Vec3.h"
#include "CarbonEngine/Math/WeightedFilter.h"
#include "CarbonEngine/Physics/PhysicsInterface.h"
#include "CarbonEngine/Physics/PhysicsIntersectResult.h"
#include "CarbonEngine/Platform/Console.h"
#include "CarbonEngine/Platform/ConsoleCommand.h"
#include "CarbonEngine/Platform/ForceFeedbackEffects.h"
#include "CarbonEngine/Platform/FrameTimers.h"
#include "CarbonEngine/Platform/GameControllerState.h"
#include "CarbonEngine/Platform/KeyConstant.h"
#include "CarbonEngine/Platform/MouseButton.h"
#include "CarbonEngine/Platform/PeriodicTimer.h"
#include "CarbonEngine/Platform/PlatformEvents.h"
#include "CarbonEngine/Platform/PlatformInterface.h"
#include "CarbonEngine/Platform/Resolution.h"
#include "CarbonEngine/Platform/ScopedTimer.h"
#include "CarbonEngine/Platform/SimpleTimer.h"
#include "CarbonEngine/Platform/TextInput.h"
#include "CarbonEngine/Platform/ThemeManager.h"
#include "CarbonEngine/Render/DataBufferManager.h"
#include "CarbonEngine/Render/DrawItem.h"
#include "CarbonEngine/Render/EffectManager.h"
#include "CarbonEngine/Render/EffectQueue.h"
#include "CarbonEngine/Render/EffectQueueArray.h"
#include "CarbonEngine/Render/Font.h"
#include "CarbonEngine/Render/FontManager.h"
#include "CarbonEngine/Render/GeometryChunk.h"
#include "CarbonEngine/Render/Renderer.h"
#include "CarbonEngine/Render/RenderEvents.h"
#include "CarbonEngine/Render/RenderQueueItem.h"
#include "CarbonEngine/Render/RenderQueueItemArray.h"
#include "CarbonEngine/Render/RenderTarget.h"
#include "CarbonEngine/Render/Shaders/AmbientOcclusionGLSL.h"
#include "CarbonEngine/Render/Shaders/Blending.h"
#include "CarbonEngine/Render/Shaders/DecalMappingGLSL.h"
#include "CarbonEngine/Render/Shaders/ParallaxMappingGLSL.h"
#include "CarbonEngine/Render/Shaders/Shader.h"
#include "CarbonEngine/Render/Shaders/ShaderRegistry.h"
#include "CarbonEngine/Render/Shaders/ShadowMappingGLSL.h"
#include "CarbonEngine/Render/Shaders/SkeletalAnimationGLSL.h"
#include "CarbonEngine/Render/Shaders/SpecularGLSL.h"
#include "CarbonEngine/Render/Texture/Texture.h"
#include "CarbonEngine/Render/Texture/Texture2D.h"
#include "CarbonEngine/Render/Texture/Texture3D.h"
#include "CarbonEngine/Render/Texture/TextureCubemap.h"
#include "CarbonEngine/Render/Texture/TextureManager.h"
#include "CarbonEngine/Render/Texture/TextureProperties.h"
#include "CarbonEngine/Render/VertexStream.h"
#include "CarbonEngine/Scene/ABTCompiler.h"
#include "CarbonEngine/Scene/Camera.h"
#include "CarbonEngine/Scene/ComplexEntity.h"
#include "CarbonEngine/Scene/CullingNode.h"
#include "CarbonEngine/Scene/Entity.h"
#include "CarbonEngine/Scene/EntityController/AlphaFadeEntityController.h"
#include "CarbonEngine/Scene/EntityController/EntityController.h"
#include "CarbonEngine/Scene/EntityController/PlatformerEntityController.h"
#include "CarbonEngine/Scene/EntityController/PlayerEntityController.h"
#include "CarbonEngine/Scene/EntityController/SetOrientationEntityController.h"
#include "CarbonEngine/Scene/EntityController/TargetPositionEntityController.h"
#include "CarbonEngine/Scene/GeometryGather.h"
#include "CarbonEngine/Scene/GUI/GUIButton.h"
#include "CarbonEngine/Scene/GUI/GUICombobox.h"
#include "CarbonEngine/Scene/GUI/GUIConsoleWindow.h"
#include "CarbonEngine/Scene/GUI/GUIEditbox.h"
#include "CarbonEngine/Scene/GUI/GUIEvents.h"
#include "CarbonEngine/Scene/GUI/GUILabel.h"
#include "CarbonEngine/Scene/GUI/GUIMousePointer.h"
#include "CarbonEngine/Scene/GUI/GUIProgressBar.h"
#include "CarbonEngine/Scene/GUI/GUISlider.h"
#include "CarbonEngine/Scene/GUI/GUIWindow.h"
#include "CarbonEngine/Scene/IntersectionResult.h"
#include "CarbonEngine/Scene/Light.h"
#include "CarbonEngine/Scene/Material.h"
#include "CarbonEngine/Scene/MaterialManager.h"
#include "CarbonEngine/Scene/Mesh/Mesh.h"
#include "CarbonEngine/Scene/Mesh/MeshFormatRegistry.h"
#include "CarbonEngine/Scene/Mesh/MeshManager.h"
#include "CarbonEngine/Scene/Region.h"
#include "CarbonEngine/Scene/Scene.h"
#include "CarbonEngine/Scene/SceneEvents.h"
#include "CarbonEngine/Scene/SkeletalAnimation.h"
#include "CarbonEngine/Scene/SkeletalMesh.h"
#include "CarbonEngine/Scene/SkyDome.h"
#include "CarbonEngine/Scene/SoundEmitter.h"
#include "CarbonEngine/Scene/SoundListener.h"
#include "CarbonEngine/Scene/Terrain.h"
#include "CarbonEngine/Scripting/ScriptManager.h"
#include "CarbonEngine/Sound/SoundEvents.h"
#include "CarbonEngine/Sound/SoundFormatRegistry.h"
#include "CarbonEngine/Sound/SoundInterface.h"
#include "CarbonEngine/Sound/SoundShader.h"
#include "CarbonEngine/Sound/SoundShaderManager.h"

// Automatically link with the appropriate library on MSVC
#ifdef _MSC_VER
    #ifdef _DEBUG
        #ifdef CARBON_64BIT
            #pragma comment(lib, "CarbonEngineDebug64.lib")
        #else
            #pragma comment(lib, "CarbonEngineDebug.lib")
        #endif
    #else
        #ifdef CARBON_64BIT
            #pragma comment(lib, "CarbonEngine64.lib")
        #else
            #pragma comment(lib, "CarbonEngine.lib")
        #endif
    #endif
#endif
